export interface Customer {
    CustomerNo: string,
    CustomerName: string,
    City: string,
    State: string,
    ZipCode: string,
    CountryCode: string,
    CustomerType: string,
    DateLastActivity: string,
    DateCreated: string,
    DateUpdated: string,
    TelephoneNo: string,
    CustomerStatus: string,
    CustomerDiscountRate: string,
    AddressLine1: string,
    AddressLine2: string,
    AddressLine3: string,
    SalespersonDivisionNo: string,
    SalespersonNo: string,
    Comment: string,
    TermsCode: string
}