export interface Item{
    category1: string,
    category2: string,
    category3: string,
    category4: string,
    dateCreated: string,
    dateUpdate: string,
    extendeddescriptionDate: string,
    imageFile: string,
    inactiveItem: string,
    itemCode: string,
    itemcodeDesc: string,
    itemType: string,
    lastsoldDate: string,
    primaryvendorNo: string,
    productLine: string,
    productType: string,
    shipWeight: string,
    standartunitCost: number,
    standartunitPrice: number,
    timeCreated: string,
    timeUpdated: string,
    volume:number,
}