export interface SaleOrder {
    CustomerNo: string,
    CustomerPONo: string,
    SalesOrderN: string,
    PurchaseOrderNo: string,
    BillToName: string,
    OrderStatus: string,
    ShipVia: string,
    WarehouseCode: string,
    ShipToCity: string,
    ShipToState: string,
    ShipToZipCode: string,
    DiscountAmt: number,
    ShipToName: string,
    ShipToAddress1: string,
    ShipToAddress2: string,
    ShipToCountryCode: string,
    ShipExpireDate: string,
    OrderDate: string,
    DateCreated: string,
    DateUpdated: string,
    VendorNo: string,
    SalespersonName: string,
    SalespersonNo: string,
    TermsCode: string,
    Comment: string,
    Detail: any
}